[package]
name = "avc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.10"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.0"
flate2 = "1.0"